feat: Initial
devops-kung-fu/ittosai pull request #1
Opened 2021-06-02 18:45 UTC by juliojimenez

2021-06-03 15:35 UTC, djschleen requested changes
- release.yml has hinge in there
- can you add the auto SBoM stuff from Hookz in here?

2021-06-03 15:35 UTC, djschleen commented on .github/workflows/release.yml
> +name: hinge Release
hinge => Ittosai

2021-06-04 16:42 UTC, juliojimenez commented on .github/workflows/release.yml
> +name: hinge Release
Good to go.

2021-06-04 16:47 UTC, djschleen approved these changes

2021-06-04 16:50 UTC, merged